name: CI lint-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [backend, frontend]

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint || echo "No linter"

    - name: Run tests
      run: npm test || echo "No tests"
