name: Deploy to Azure VM

on:
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/cd-build-push.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker system prune -f
